project 'Tetris.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Tetris' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tetris
  pod 'SKSpriteButton', :git => 'https://github.com/hanjoes/SKSpriteButton.git' 

  target 'TetrisTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
  end

  target 'TetrisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
